import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className='w-full max-w-5xl mx-auto mt-5'>
					<Header />
					<main>
						{children}
					</main>
				</div>
			</body>
		</html>
	)
}
